package com.zxr.medicalaid;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MEDICAL_LIST.
 */
public class MedicalList {

    private String date;
    private String name;
    private String weight;
    private String patient;

    public MedicalList() {
    }

    public MedicalList(String date, String name, String weight, String patient) {
        this.date = date;
        this.name = name;
        this.weight = weight;
        this.patient = patient;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getPatient() {
        return patient;
    }

    public void setPatient(String patient) {
        this.patient = patient;
    }

}
