package com.zxr.medicalaid;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.zxr.medicalaid.MedicalDateInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MEDICAL_DATE_INFO.
*/
public class MedicalDateInfoDao extends AbstractDao<MedicalDateInfo, Long> {

    public static final String TABLENAME = "MEDICAL_DATE_INFO";

    /**
     * Properties of entity MedicalDateInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DrawerNum = new Property(1, Integer.class, "drawerNum", false, "DRAWER_NUM");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property ProductDate = new Property(3, String.class, "productDate", false, "PRODUCT_DATE");
        public final static Property ShelfLife = new Property(4, String.class, "shelfLife", false, "SHELF_LIFE");
    };


    public MedicalDateInfoDao(DaoConfig config) {
        super(config);
    }
    
    public MedicalDateInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MEDICAL_DATE_INFO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'DRAWER_NUM' INTEGER," + // 1: drawerNum
                "'NAME' TEXT," + // 2: name
                "'PRODUCT_DATE' TEXT," + // 3: productDate
                "'SHELF_LIFE' TEXT);"); // 4: shelfLife
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MEDICAL_DATE_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MedicalDateInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer drawerNum = entity.getDrawerNum();
        if (drawerNum != null) {
            stmt.bindLong(2, drawerNum);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String productDate = entity.getProductDate();
        if (productDate != null) {
            stmt.bindString(4, productDate);
        }
 
        String shelfLife = entity.getShelfLife();
        if (shelfLife != null) {
            stmt.bindString(5, shelfLife);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MedicalDateInfo readEntity(Cursor cursor, int offset) {
        MedicalDateInfo entity = new MedicalDateInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // drawerNum
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // productDate
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // shelfLife
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MedicalDateInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDrawerNum(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setProductDate(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setShelfLife(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MedicalDateInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MedicalDateInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
