package com.zxr.medicalaid;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    private String idString;
    private String uName;
    private String phoneNumber;
    private String password;
    private String type;
    private Integer isAlready;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String idString, String uName, String phoneNumber, String password, String type, Integer isAlready) {
        this.id = id;
        this.idString = idString;
        this.uName = uName;
        this.phoneNumber = phoneNumber;
        this.password = password;
        this.type = type;
        this.isAlready = isAlready;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdString() {
        return idString;
    }

    public void setIdString(String idString) {
        this.idString = idString;
    }

    public String getUName() {
        return uName;
    }

    public void setUName(String uName) {
        this.uName = uName;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getIsAlready() {
        return isAlready;
    }

    public void setIsAlready(Integer isAlready) {
        this.isAlready = isAlready;
    }

}
